GET http://localhost:10000/api/ingredientes

###

GET http://localhost:1001/api/recetas

###

POST http://localhost:1001/api/ingredientes
Content-Type: application/json

{
    "nombre":"Bacardi", 
    "tipo_insumo":"Destilados", 
    "cantidad_ml":500, 
    "unidad_medida":"ml", 
    "precio":1500
}

### Actualizar
PATCH http://localhost:1001/api/ingredientes/33156f30-e002-40ed-aaff-7ff9a89b148e
Content-Type: application/json

{
    "cantidad_botellas" : 5
}

### Borrar

PATCH  http://localhost:1001/api/ingredientes/fe9ed862-f2d8-42cb-97dd-113bc40a30cb

